### ISSUE TITLE
just display raw <i><a> 

### ISSUE THREAD

**Issue by uuangian** [celsomiranda/hexo-renderer-markdown-it#10]
On http://localhost:4000/  page, the tags `<i class="fa fa-camera-retro"></i> ` or `<a id="nav-googleplus-link" class="nav-icon" href="https://plus.google.com/" target="_blank"></a>` just they are, but hexo-renderer-marked display the very icons. 
So i am not sure there is any settings about these tags.

**Comment by celsomiranda** [comment]
Can you be more specific?

Ideally you could point me to a repo with the code you're talking about.

This plugin shouldn't touch anything that's html related, just the source `md` files.

**Comment by uuangian** [comment]
I find the problem like this, for example, the md text
```markdown
Hey! I'm your first Markdown document in **StackEdit**[^stackedit]. Don't delete me, I'm very helpful! I can be recovered anyway in the **Utils** tab of the <i class="icon-cog"></i> **Settings** dialog.
```
`<i class="icon-cog"></i>` in index.html hexo generated is writen by `&lt;i class=&quot;icon-cog&quot;&gt;&lt;/i&gt;` , so the tag cannot be parsed

**Comment by celsomiranda** [comment]
Check the [Documentation for advanced configutation](https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/Advanced-Configuration).

If you notice the very first parameter you can config (`html`), you'll see you can make the plugin behave like you want.

I've just checked and the option does work fine, so I'm guessing you just set the proper configuration in your `_config.yml`.

I'm not sure about the `**StackEdit**[^stackedit]` part, what is it suposed to render?
