### ISSUE TITLE
Issues with <!--more-->

### ISSUE THREAD

**Issue by JoshPAT** [celsomiranda/hexo-renderer-markdown-it#14]
When  I applied the plugins ,   in my post doesn't function anymore.

**Comment by celsomiranda** [comment]
I'm away for the next few days, but I use that function and never had any trouble with it.

**Comment by lcyan** [comment]
The same problem so am i

**Comment by celsomiranda** [comment]
What theme are you using?

**Comment by lcyan** [comment]
[jacman](https://github.com/wuchong/jacman)

**Comment by celsomiranda** [comment]
Hexo parses the post before it does the markdown conversion, looking for tags and , so the renderer shouldn't interfere with that process.

I'm going to try jacman as soon as I can, but my best bet is that there's something wrong with Hexo, or the theme itself.

Does this behaviour happen if `hexo-renderer-marked` is used instead of this render?

**Comment by lcyan** [comment]
With `hexo-renderer-marked ` to render is normal

[jacman](http://wuchong.me/jacman/)

**Comment by JoshPAT** [comment]
I am using theme yilia, if I use the default setting of `hexo-renderer-markdown-it`, there would be no problem. However, if I introduce plugins like `footnotes`, then  malfunctions.

**Comment by MHerbst** [comment]
I have got the same problem with the standard landscape theme. Even if no plugin is activated "" does not work. At some point the less-than and greater-than characters are escaped and replaced by &lt; resp. &gt; and it is no longer recognized as a comment.

With other themes, e.g. Icarus there is no problem.

**Comment by lcyan** [comment]
**When I configure the following options,  work as normal**
@MHerbst @JoshPAT 
```bash
markdown:
      render:
          html: true
```

**Comment by celsomiranda** [comment]
That makes sense. The problem was that the plugin was escaping the HTML
provided by the tag filter.

Closing


2015-06-08 6:13 GMT+01:00 molloc <notifications@github.com>:
