### ISSUE TITLE
Allow option passthrough for plugins

### ISSUE THREAD

**Issue by mshick** [celsomiranda/hexo-renderer-markdown-it#29]
This is a fairly minor change, but simply allowing the plugins array to contain objects as well as strings enables this plugin to be much more flexible. It might even resolve some of the other issues in the queue here. 

Simply put, `markdown-it` is extensible and easy enough -- I don't think this module should attempt to proxy all the settings for all the plugins, but should instead just be a thin layer between the hexo renderer hook, the core module and the various plugins.

I made a PR for this already (#28). It was 2 lines of code different. Tests included.

**Comment by celsomiranda** [comment]
Merged it. I'll test it ASAP and publish the new version to NPM.

Thanks!
