### ISSUE TITLE
Footnotes not working

### ISSUE THREAD

**Issue by MattieTK** [celsomiranda/hexo-renderer-markdown-it#33]
Hi guys,

I've tried this across multiple themes now but I can't seem to get this working outside of the https://markdown-it.github.io/ demo

My example is:

```
test [^1]

[^1]: test
```

But this only works in the demo where it correctly outputs

```
<p>Test <sup class="footnote-ref"><a href="#fn1" id="fnref1">[1]</a></sup></p>
<hr class="footnotes-sep">
<section class="footnotes">
<ol class="footnotes-list">
<li id="fn1"  class="footnote-item"><p>test <a href="#fnref1" class="footnote-backref">↩</a></p>
</li>
</ol>
</section>
```

On my hexo install it outputs

```
The 2.2% of the playerbase generating 46% of the revenue [^1]
```
Then lots of text
Then the footnotes section
```
[^1]: http://www.gamesindustry.biz/articles/2014-04-09-only-2-2-percent-of-free-to-play-users-ever-pay-report
```

And it just outputs the tags in text. So the parser is not picking them up properly, but it seems to be picking up everything else.

I've made no changes in the root `_config.yml` file regarding `markdown`, I'm not sure if I was supposed to when installing the plugin and removing the default.

**Comment by celsomiranda** [comment]
Please, read [this repo's wiki](https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki) You need to configure it and tell it what plugins you'd like to use.
